### ISSUE TITLE
Maybe deps wrong.

### ISSUE THREAD

**Issue by keelii** [mardix/assembly#1]
when i first run assembly app, it comes error below:

```bash
➜  asm-project asm-admin serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/webassets/loaders.py", line 43, in __init__
    yaml
NameError: name 'yaml' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/asm-admin", line 11, in <module>
    load_entry_point('Assembly==1.0.0', 'console_scripts', 'asm-admin')()
  File "/usr/local/lib/python3.7/site-packages/assembly/cli.py", line 245, in cmd
    entry = import_string(ENTRY_PY.replace('.py', ''))
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 546, in import_string
    __import__(import_name)
  File "/Users/zhouqili/Desktop/asm-project/wsgi.py", line 60, in <module>
    app = Assembly.init(__name__, APPS)
  File "/usr/local/lib/python3.7/site-packages/assembly/assembly.py", line 307, in init
    [cls.assets.from_yaml(a) for a in cls._asset_bundles]
  File "/usr/local/lib/python3.7/site-packages/assembly/assembly.py", line 307, in <listcomp>
    [cls.assets.from_yaml(a) for a in cls._asset_bundles]
  File "/usr/local/lib/python3.7/site-packages/flask_assets.py", line 363, in from_yaml
    bundles = YAMLLoader(path).load_bundles()
  File "/usr/local/lib/python3.7/site-packages/webassets/loaders.py", line 45, in __init__
    raise EnvironmentError('PyYAML is not installed')
webassets.exceptions.EnvironmentError: PyYAML is not installed
➜  asm-project 

```

**Comment by keelii** [comment]
BTW i install assembly globally.

**Comment by mardix** [comment]
Hi thanks for your interest in Assembly. 

I just pushed version 1.0.1 which adds the "yaml" dependency.

Try to reinstall it with the code below

`pip install --upgrade --force-reinstall assembly`

or you can just do "pip install yaml"

Thanks

**Comment by keelii** [comment]
@mardix It's OK now~
